[project]
name = "py-decs"
version = "0.5.14"
description = "A declarative html scraper for python"
authors = [
    { name = "Vincent Lonij", email = "29819815+vincentropy@users.noreply.github.com" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4 (>=4.14.3,<5.0.0)",
    "pydantic (>=2.12.5,<3.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "lxml (>=6.0.4,<7.0.0)",
    "click (>=8.3.2,<9.0.0)",
]

[project.scripts]
decs = "py_decs.cli:cli"

[tool.poetry]

[tool.poetry.group.dev.dependencies]
mypy = "^1.20.0"
types-pyyaml = "^6.0.12.20260408"
pylint = "^4.0.5"
pytest = "^9.0.3"
types-lxml = "^2026.2.16"
pylint-pydantic = "^0.4.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint]
load-plugins = ["pylint_pydantic"]
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "line-too-long",
]
max-line-length = 120

[tool.black]
line-length = 120
